# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

E_fun_C <- function(i, pi_mat, rankIndex_list, mu_e, Sig_e, Omg_e, burn_num, restore_num) {
    .Call(`_mlThurstone_E_fun_C`, i, pi_mat, rankIndex_list, mu_e, Sig_e, Omg_e, burn_num, restore_num)
}

rtn <- function(Mean, Sd, Low, High) {
    .Call(`_mlThurstone_rtn`, Mean, Sd, Low, High)
}

