// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// E_fun_C
Rcpp::List E_fun_C(int i, arma::umat pi_mat, Rcpp::List rankIndex_list, arma::colvec mu_e, arma::mat Sig_e, arma::mat Omg_e, int burn_num, int restore_num);
RcppExport SEXP _test2_E_fun_C(SEXP iSEXP, SEXP pi_matSEXP, SEXP rankIndex_listSEXP, SEXP mu_eSEXP, SEXP Sig_eSEXP, SEXP Omg_eSEXP, SEXP burn_numSEXP, SEXP restore_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type pi_mat(pi_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type rankIndex_list(rankIndex_listSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type mu_e(mu_eSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sig_e(Sig_eSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omg_e(Omg_eSEXP);
    Rcpp::traits::input_parameter< int >::type burn_num(burn_numSEXP);
    Rcpp::traits::input_parameter< int >::type restore_num(restore_numSEXP);
    rcpp_result_gen = Rcpp::wrap(E_fun_C(i, pi_mat, rankIndex_list, mu_e, Sig_e, Omg_e, burn_num, restore_num));
    return rcpp_result_gen;
END_RCPP
}
// rtn
double rtn(double Mean, double Sd, double Low, double High);
RcppExport SEXP _test2_rtn(SEXP MeanSEXP, SEXP SdSEXP, SEXP LowSEXP, SEXP HighSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Mean(MeanSEXP);
    Rcpp::traits::input_parameter< double >::type Sd(SdSEXP);
    Rcpp::traits::input_parameter< double >::type Low(LowSEXP);
    Rcpp::traits::input_parameter< double >::type High(HighSEXP);
    rcpp_result_gen = Rcpp::wrap(rtn(Mean, Sd, Low, High));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_test2_E_fun_C", (DL_FUNC) &_test2_E_fun_C, 8},
    {"_test2_rtn", (DL_FUNC) &_test2_rtn, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_test2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
