# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_test1_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_test1_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_test1_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_test1_rcpparma_bothproducts`, x)
}

mycall <- function(x, y, i, z) {
    .Call(`_test1_mycall`, x, y, i, z)
}

rtnRcpp <- function(mean, sd, low, 'Inf']) {
    .Call(`_test1_rtnRcpp`, mean, sd, low, 'Inf'])
}

